"""
catalog.sources.remote — RemoteModelsDevSource: cached, offline-tolerant models.dev fetch.

The opt-in network source. Fetches models.dev's `api.json` once, caches it to a path the
*consumer* supplies (this module knows nothing about `~/.visvoai`), and serves from cache
within a TTL. Degrades, never raises:

    cache fresh (< ttl)   → use cache
    else fetch ok         → overwrite cache, use it
    else stale cache      → use it (logged)
    else (no cache)       → empty (the catalog engine falls back to BakedSource)

Stdlib only (`urllib`) — keeps visvoai-ai offline-pure and dependency-light. The fetch is
injectable (`fetcher=`) so tests never touch the network.
"""
from __future__ import annotations

import gzip
import json
import logging
import os
import time
import urllib.request
from importlib.resources import files
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from visvoai.ai.catalog.engine import CatalogSource
from visvoai.ai.catalog.sources.modelsdev import ModelsDevSource
from visvoai.ai.model_registry import ModelDefinition

logger = logging.getLogger(__name__)

DEFAULT_URL = "https://models.dev/api.json"
DEFAULT_TTL_SECONDS = 24 * 60 * 60  # a day — model facts don't change hourly
_SNAPSHOT_RESOURCE = "modelsdev_snapshot.json.gz"  # bundled offline floor (catalog/data/)


def load_bundled_snapshot() -> Optional[Dict[str, Any]]:
    """The models.dev snapshot shipped in the package — the OpenAI-compat offline floor.
    Generated by scripts/generate_modelsdev_snapshot.py. None if absent/unreadable."""
    try:
        data = (files("visvoai.ai.catalog.data") / _SNAPSHOT_RESOURCE).read_bytes()
        return json.loads(gzip.decompress(data))
    except (FileNotFoundError, ModuleNotFoundError, OSError, ValueError):
        return None


class RemoteModelsDevSource(CatalogSource):
    """models.dev as a cached CatalogSource. Construct with the cache path the consumer
    owns; opt into refresh by leaving the cache stale."""

    def __init__(
        self,
        cache_path: os.PathLike | str,
        *,
        url: str = DEFAULT_URL,
        ttl_seconds: int = DEFAULT_TTL_SECONDS,
        timeout: int = 20,
        fetcher: Optional[Callable[[], Dict[str, Any]]] = None,
        use_bundled_fallback: bool = True,
    ) -> None:
        self._cache_path = Path(cache_path)
        self._url = url
        self._ttl = ttl_seconds
        self._timeout = timeout
        self._fetcher = fetcher or self._http_get
        self._use_bundled_fallback = use_bundled_fallback

    # ── the source contract ───────────────────────────────────────────────────
    def models(self) -> List[ModelDefinition]:
        catalog = self._resolve_catalog()
        if not catalog:
            logger.info("remote: no models.dev catalog available — yielding nothing (baked floor applies)")
            return []
        return ModelsDevSource(catalog).models()

    # ── resolution: fresh cache → fetch → stale cache → none ──────────────────
    def _resolve_catalog(self) -> Optional[Dict[str, Any]]:
        if self._cache_fresh():
            cached = self._load_cache()
            if cached is not None:
                return cached  # fresh + readable → done, no network
        try:
            data = self._fetcher()
            self._write_cache(data)
            logger.info("remote: refreshed models.dev catalog (%d providers)", len(data))
            return data
        except Exception as e:  # network/parse boundary — degrade to cache, don't crash
            logger.warning("remote: models.dev fetch failed (%s: %s) — falling back to cache",
                           type(e).__name__, str(e)[:120])
            cached = self._load_cache()
            if cached is not None:
                return cached
            if self._use_bundled_fallback:
                snap = load_bundled_snapshot()
                if snap is not None:
                    logger.info("remote: using bundled models.dev snapshot (offline floor)")
                return snap
            return None

    # ── cache + fetch helpers ─────────────────────────────────────────────────
    def _cache_fresh(self) -> bool:
        try:
            age = time.time() - os.path.getmtime(self._cache_path)
            return age < self._ttl
        except OSError:
            return False

    def _load_cache(self) -> Optional[Dict[str, Any]]:
        try:
            return json.loads(self._cache_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None

    def _write_cache(self, data: Dict[str, Any]) -> None:
        try:
            self._cache_path.parent.mkdir(parents=True, exist_ok=True)
            tmp = self._cache_path.with_suffix(self._cache_path.suffix + ".tmp")
            tmp.write_text(json.dumps(data), encoding="utf-8")
            os.replace(tmp, self._cache_path)  # atomic
        except OSError as e:
            logger.warning("remote: could not write cache %s (%s)", self._cache_path, e)

    def _http_get(self) -> Dict[str, Any]:
        req = urllib.request.Request(self._url, headers={"User-Agent": "visvoai-ai"})
        with urllib.request.urlopen(req, timeout=self._timeout) as resp:  # noqa: S310 (https url)
            return json.loads(resp.read().decode("utf-8"))
